spring.application.name=RGR
spring.datasource.url=jdbc:mysql://localhost:3306/lilubrary
spring.datasource.username=root
spring.datasource.password=1982
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
